### ISSUE TITLE
Installation and test problems!

### ISSUE THREAD

**Issue by smallcaiyuan** [fatiando/fatiando#234]
Hi，
    I met some errors when I run two recipes from the Cookbook (in Linux). Before the test of recipes, the Anaconda and fatiando are installed under my account (not the root account) without any problem. I am fresh to python and fatiando, so would you like to help me  solve these errors? 

```
The 1st recipe is  gravmag_2d_polygon_picker.py. The command and error message are given below:
   wy@wy Downloads]$ python gravmag_2d_polygon_picker.py 
   Traceback (most recent call last):
    File "gravmag_2d_polygon_picker.py", line 5, in <module>
    from fatiando import utils, mesher
    ImportError: No module named fatiando
```

   The second recipe is seismic_wavefd_scalar.py.   The corresponding message is here
          [wy@wy Downloads]$ python seismic_wavefd_scalar.py 
         Traceback (most recent call last):
          File "seismic_wavefd_scalar.py", line 10, in <module>
          from matplotlib import animation
          ImportError: cannot import name animation

  Next are some other basic information:
         OS：Red Hat Enterprise Linux 6
         （Linux wy 2.6.32-358.el6.i686 #1 SMP Tue Jan 29 11:48:01 EST 2013 i686 i686 i386 GNU/Linux）
         Version of Fatiando ：0.3
         Python distribution：Anaconda
         Python version：2.7

```
    Thank you !
```

Best wishes!

**Comment by leouieda** [comment]
Hi @smallcaiyuan, I see that you've closed the issue. Were you able to resolve the problem?

**Comment by smallcaiyuan** [comment]
@leouieda   I'm sorry, I don't know why is was closed. The title also was changed. The problem is not solved. Thank you!

**Comment by leouieda** [comment]
@smallcaiyuan can you
